/**
 * End-to-end devnet smoke test for clustly-escrow.
 *
 * What this does (all on live Solana devnet):
 *   1. Creates a test USDC mint we control (6 decimals)
 *   2. Calls initialize_config (admin = our wallet, fee_bps=400) — idempotent
 *   3. Creates fresh poster + claimer keypairs, airdrops SOL, mints test-USDC
 *   4. Walks a task through: init → enroll → submit → approve
 *   5. Verifies balances: claimer +4.80 USDC, fee_vault +0.20 USDC
 *   6. Prints a Solscan link for every tx so you can inspect manually
 *
 * Run:
 *   cd solana && npx ts-node scripts/e2e-devnet.ts
 *
 * Note: config is a singleton PDA. First run initializes it; subsequent runs
 * reuse it. The mint pinned at init is used for all future tasks.
 */

import * as anchor from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
  LAMPORTS_PER_SOL,
  Connection,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  getAssociatedTokenAddress,
  getAccount,
} from "@solana/spl-token";
import * as fs from "fs";
import * as path from "path";

const PROGRAM_ID = new PublicKey("8pnWWX45FL6WmzP38bfrxjxKKAkwwWPUhkP7iRwarv8K");
const DEVNET_URL = "https://api.devnet.solana.com";
const CONFIG_SEED = Buffer.from("config");
const TASK_SEED = Buffer.from("task");
const CLAIM_SEED = Buffer.from("claim");
const DECIMALS = 6;

function solscan(sig: string): string {
  return `https://solscan.io/tx/${sig}?cluster=devnet`;
}
function solscanAcct(addr: PublicKey): string {
  return `https://solscan.io/account/${addr.toBase58()}?cluster=devnet`;
}
function usdc(amount: number): bigint {
  return BigInt(Math.round(amount * 10 ** DECIMALS));
}
function randomId16(): Buffer {
  const b = Buffer.alloc(16);
  for (let i = 0; i < 16; i++) b[i] = Math.floor(Math.random() * 256);
  return b;
}
function loadKeypair(p: string): Keypair {
  const raw = JSON.parse(fs.readFileSync(p, "utf8"));
  return Keypair.fromSecretKey(Uint8Array.from(raw));
}

async function transferSol(
  conn: Connection,
  from: Keypair,
  to: PublicKey,
  sol: number
) {
  const tx = new (await import("@solana/web3.js")).Transaction().add(
    SystemProgram.transfer({
      fromPubkey: from.publicKey,
      toPubkey: to,
      lamports: Math.round(sol * LAMPORTS_PER_SOL),
    })
  );
  const { sendAndConfirmTransaction } = await import("@solana/web3.js");
  return sendAndConfirmTransaction(conn, tx, [from], { commitment: "confirmed" });
}

async function balance(conn: Connection, ata: PublicKey): Promise<bigint> {
  try {
    return (await getAccount(conn, ata)).amount;
  } catch {
    return 0n;
  }
}

const log = {
  step: (n: number, title: string) =>
    console.log(`\n━━━ Step ${n}: ${title} ━━━`),
  kv: (k: string, v: string) => console.log(`  ${k.padEnd(22)} ${v}`),
  tx: (label: string, sig: string) => {
    console.log(`  ${label.padEnd(22)} ${sig}`);
    console.log(`  ${"".padEnd(22)} ↳ ${solscan(sig)}`);
  },
};

async function main() {
  // ── Connection + provider setup ─────────────────────────────
  const connection = new Connection(DEVNET_URL, "confirmed");
  const walletPath =
    process.env.ANCHOR_WALLET ?? path.join(process.env.HOME!, ".config/solana/id.json");
  const wallet = new anchor.Wallet(loadKeypair(walletPath));
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  anchor.setProvider(provider);

  // Load the IDL generated by anchor build.
  const idlPath = path.join(__dirname, "..", "target", "idl", "clustly_escrow.json");
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));
  const program = new anchor.Program(idl, provider);

  console.log(`Program: ${PROGRAM_ID.toBase58()}`);
  console.log(`Payer:   ${wallet.publicKey.toBase58()}`);
  console.log(`RPC:     ${DEVNET_URL}`);

  // ── Step 1: create a test USDC mint we control ─────────────
  log.step(1, "Create test USDC mint");
  const mintAuthority = wallet.payer;
  const testMint = await createMint(
    connection,
    mintAuthority,
    mintAuthority.publicKey,
    null,
    DECIMALS
  );
  log.kv("test USDC mint", testMint.toBase58());
  log.kv("Solscan", solscanAcct(testMint));

  // ── Step 2: initialize_config (idempotent) ─────────────────
  log.step(2, "Initialize config");
  const [configPda] = PublicKey.findProgramAddressSync([CONFIG_SEED], PROGRAM_ID);
  const feeVaultAta = await getAssociatedTokenAddress(testMint, configPda, true);
  log.kv("config PDA", configPda.toBase58());
  log.kv("fee_vault ATA", feeVaultAta.toBase58());

  let configExists = false;
  try {
    await program.account.escrowConfig.fetch(configPda);
    configExists = true;
  } catch {
    /* not initialized */
  }

  if (configExists) {
    console.log("  (config already initialized, reusing)");
  } else {
    const sig = await program.methods
      .initializeConfig(wallet.publicKey, 400)
      .accountsStrict({
        payer: wallet.publicKey,
        config: configPda,
        usdcMint: testMint,
        feeVault: feeVaultAta,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .rpc();
    log.tx("initialize_config", sig);
  }

  const cfg = await program.account.escrowConfig.fetch(configPda);
  log.kv("admin", cfg.admin.toBase58());
  log.kv("mint (pinned)", cfg.usdcMint.toBase58());
  log.kv("fee_bps", String(cfg.feeBps));

  // If a prior run pinned a different mint, we cannot use this script's new mint.
  if (cfg.usdcMint.toBase58() !== testMint.toBase58()) {
    console.log(
      `\n⚠ Config is pinned to a different mint (${cfg.usdcMint.toBase58()}).\n` +
        `  Using the pinned mint for the rest of this run.`
    );
  }
  const activeMint = new PublicKey(cfg.usdcMint);
  // If we reused a pinned mint, we may not have mint authority. That's fine as long as
  // the pinned mint's authority lets us mint test tokens — for this script, it IS us.
  const activeFeeVaultAta = await getAssociatedTokenAddress(activeMint, configPda, true);

  // ── Step 3: fresh poster + claimer, fund them ─────────────
  log.step(3, "Create fresh poster + claimer, fund them");
  const poster = Keypair.generate();
  const claimer = Keypair.generate();
  log.kv("poster", poster.publicKey.toBase58());
  log.kv("claimer", claimer.publicKey.toBase58());

  // Fund from our main wallet (devnet faucet is unreliable; we already hold SOL).
  await transferSol(connection, wallet.payer, poster.publicKey, 0.3);
  await transferSol(connection, wallet.payer, claimer.publicKey, 0.1);
  log.kv("funded poster", "0.3 SOL");
  log.kv("funded claimer", "0.1 SOL");

  const posterAta = await createAssociatedTokenAccount(
    connection,
    wallet.payer,
    activeMint,
    poster.publicKey
  );
  const mintSig = await mintTo(
    connection,
    wallet.payer,
    activeMint,
    posterAta,
    mintAuthority,
    Number(usdc(100))
  );
  log.tx("mint 100 USDC → poster", mintSig);

  // ── Step 4: initialize_task (5 USDC bounty, 1 slot) ───────
  log.step(4, "initialize_task");
  const taskId = randomId16();
  const [taskPda] = PublicKey.findProgramAddressSync(
    [TASK_SEED, taskId],
    PROGRAM_ID
  );
  const taskVault = await getAssociatedTokenAddress(activeMint, taskPda, true);
  log.kv("task_id (hex)", taskId.toString("hex"));
  log.kv("task PDA", taskPda.toBase58());
  log.kv("task_vault ATA", taskVault.toBase58());

  const initTaskSig = await program.methods
    .initializeTask(
      Array.from(taskId),
      new anchor.BN(usdc(5).toString()),
      1,
      48 * 3600,
      new anchor.BN(0)
    )
    .accountsStrict({
      poster: poster.publicKey,
      config: configPda,
      usdcMint: activeMint,
      task: taskPda,
      taskVault,
      posterAta,
      systemProgram: SystemProgram.programId,
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([poster])
    .rpc();
  log.tx("initialize_task", initTaskSig);
  log.kv(
    "vault balance",
    `${Number(await balance(connection, taskVault)) / 10 ** DECIMALS} USDC`
  );

  // ── Step 5: enroll ────────────────────────────────────────
  log.step(5, "enroll");
  const claimId = randomId16();
  const [claimPda] = PublicKey.findProgramAddressSync(
    [CLAIM_SEED, claimId],
    PROGRAM_ID
  );
  log.kv("claim_id (hex)", claimId.toString("hex"));
  log.kv("claim PDA", claimPda.toBase58());

  const enrollSig = await program.methods
    .enroll(Array.from(claimId))
    .accountsStrict({
      claimer: claimer.publicKey,
      task: taskPda,
      claim: claimPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([claimer])
    .rpc();
  log.tx("enroll", enrollSig);

  // ── Step 6: submit ────────────────────────────────────────
  log.step(6, "submit");
  const deliverableHash = Buffer.alloc(32, 42);
  const submitSig = await program.methods
    .submit(Array.from(deliverableHash))
    .accountsStrict({
      claimer: claimer.publicKey,
      task: taskPda,
      claim: claimPda,
    })
    .signers([claimer])
    .rpc();
  log.tx("submit", submitSig);

  // ── Step 7: approve_claim ─────────────────────────────────
  log.step(7, "approve_claim (fee auto-routes to fee_vault)");
  const claimerAta = await getAssociatedTokenAddress(activeMint, claimer.publicKey);
  const feeVaultBefore = await balance(connection, activeFeeVaultAta);
  const approveSig = await program.methods
    .approveClaim()
    .accountsStrict({
      poster: poster.publicKey,
      config: configPda,
      usdcMint: activeMint,
      task: taskPda,
      claim: claimPda,
      taskVault,
      claimerAta,
      claimer: claimer.publicKey,
      feeVault: activeFeeVaultAta,
      systemProgram: SystemProgram.programId,
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([poster])
    .rpc();
  log.tx("approve_claim", approveSig);

  const claimerBal = await balance(connection, claimerAta);
  const vaultAfter = await balance(connection, taskVault);
  const feeVaultAfter = await balance(connection, activeFeeVaultAta);
  const feeDelta = feeVaultAfter - feeVaultBefore;

  log.kv(
    "claimer balance",
    `${Number(claimerBal) / 10 ** DECIMALS} USDC (expected 4.80)`
  );
  log.kv(
    "task_vault balance",
    `${Number(vaultAfter) / 10 ** DECIMALS} USDC (expected 0.00)`
  );
  log.kv(
    "fee_vault delta",
    `+${Number(feeDelta) / 10 ** DECIMALS} USDC (expected 0.20)`
  );

  // ── Assert ────────────────────────────────────────────────
  const ok =
    claimerBal === usdc(4.8) && vaultAfter === 0n && feeDelta === usdc(0.2);
  console.log(
    `\n${ok ? "✓ E2E PASSED" : "✗ E2E FAILED"} — devnet escrow flow verified`
  );

  // ── Summary for the results doc ───────────────────────────
  console.log("\n━━━ Summary (copy into tasks/solana-escrow-devnet-results.md) ━━━");
  console.log(`Program ID:          ${PROGRAM_ID.toBase58()}`);
  console.log(`Config PDA:          ${configPda.toBase58()}`);
  console.log(`Test USDC mint:      ${activeMint.toBase58()}`);
  console.log(`Fee vault ATA:       ${activeFeeVaultAta.toBase58()}`);
  console.log(`Poster:              ${poster.publicKey.toBase58()}`);
  console.log(`Claimer:             ${claimer.publicKey.toBase58()}`);
  console.log(`Task PDA:            ${taskPda.toBase58()}`);
  console.log(`Claim PDA:           ${claimPda.toBase58()}`);
  console.log(`initialize_task tx:  ${solscan(initTaskSig)}`);
  console.log(`enroll tx:           ${solscan(enrollSig)}`);
  console.log(`submit tx:           ${solscan(submitSig)}`);
  console.log(`approve_claim tx:    ${solscan(approveSig)}`);

  if (!ok) process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
